export default {
  //   region: "CHN",
  //   idType: 1,
  surveyInit: [
    {
      optionId: 95,
      options: [
        {
          id: 95,
          order: 1,
          optionValue: "未婚",
          questionid: 20,
          apexValue: "SINGLE",
          expression: "",
        },
        {
          id: 96,
          order: 2,
          optionValue: "已婚",
          questionid: 20,
          apexValue: "MARRIED",
          expression: "",
        },
        {
          id: 97,
          order: 3,
          optionValue: "离异",
          questionid: 20,
          apexValue: "DIVORCED",
          expression: "",
        },
        {
          id: 98,
          order: 4,
          optionValue: "丧偶",
          questionid: 20,
          apexValue: "WIDOWED",
          expression: "",
        },
      ],
      id: 20,
      question: "您的婚姻状况？",
      type: 1,
      parentId: 19,
      appField: "maritalStatus",
      title: "婚姻状况",
      expression: "",
      order: 2,
      citizenship: "",
    },
    {
      optionId: 99,
      options: [
        {
          id: 99,
          order: 1,
          optionValue: "0",
          questionid: 21,
          apexValue: "0",
          expression: "",
        },
        {
          id: 100,
          order: 2,
          optionValue: "1",
          questionid: 21,
          apexValue: "1",
          expression: "",
        },
        {
          id: 101,
          order: 3,
          optionValue: "2",
          questionid: 21,
          apexValue: "2",
          expression: "",
        },
        {
          id: 102,
          order: 4,
          optionValue: "3",
          questionid: 21,
          apexValue: "3",
          expression: "",
        },
        {
          id: 103,
          order: 5,
          optionValue: "4",
          questionid: 21,
          apexValue: "4",
          expression: "",
        },
        {
          id: 104,
          order: 6,
          optionValue: "5",
          questionid: 21,
          apexValue: "5",
          expression: "",
        },
        {
          id: 105,
          order: 7,
          optionValue: "6",
          questionid: 21,
          apexValue: "6",
          expression: "",
        },
      ],
      id: 21,
      question: "赡养人数量?",
      type: 1,
      parentId: 19,
      appField: "numDependents",
      title: "赡养人数量",
      expression: "",
      order: 3,
      citizenship: "",
    },
    {
      optionId: 106,
      options: [
        {
          id: 106,
          order: 1,
          optionValue: "在职",
          questionid: 23,
          apexValue: "EMPLOYED",
          expression: "",
        },
        {
          id: 107,
          order: 2,
          optionValue: "无业",
          questionid: 23,
          apexValue: "UNEMPLOYED",
          expression: "",
        },
        {
          id: 108,
          order: 3,
          optionValue: "退休",
          questionid: 23,
          apexValue: "RETIRED",
          expression: "",
        },
        {
          id: 109,
          order: 4,
          optionValue: "学生",
          questionid: 23,
          apexValue: "STUDENT",
          expression: "",
        },
      ],
      id: 23,
      question: "您的就业状况？",
      type: 1,
      parentId: 22,
      appField: "employmentStatus",
      title: "职业状况",
      expression: "",
      order: 5,
      citizenship: "",
    },
    {
      optionId: 110,
      options: [
        {
          id: 110,
          order: 1,
          optionValue: "董事",
          questionid: 24,
          apexValue: "CHIEFOFFICER",
          expression: "",
        },
        {
          id: 111,
          order: 2,
          optionValue: "副总裁",
          questionid: 24,
          apexValue: "VICEPRESIDENT",
          expression: "",
        },
        {
          id: 112,
          order: 3,
          optionValue: "总监",
          questionid: 24,
          apexValue: "DIRECTOR",
          expression: "",
        },
        {
          id: 113,
          order: 4,
          optionValue: "经理",
          questionid: 24,
          apexValue: "MANAGER",
          expression: "",
        },
        {
          id: 114,
          order: 5,
          optionValue: "管理人员",
          questionid: 24,
          apexValue: "ADMINISTRATOR",
          expression: "",
        },
        {
          id: 115,
          order: 6,
          optionValue: "顾问",
          questionid: 24,
          apexValue: "CONSULTANT",
          expression: "",
        },
        {
          id: 116,
          order: 7,
          optionValue: "助理",
          questionid: 24,
          apexValue: "ASSISTANT",
          expression: "",
        },
        {
          id: 117,
          order: 8,
          optionValue: "职员",
          questionid: 24,
          apexValue: "STAFF",
          expression: "",
        },
        {
          id: 350,
          order: 10,
          optionValue: "个体经营者",
          questionid: 24,
          apexValue: "SELF-EMPLOYED",
          expression: "",
        },
      ],
      id: 24,
      question: "您的职位？",
      type: 1,
      parentId: 22,
      appField: "positionEmployed",
      title: "职位",
      expression: "($23$===106)",
      order: 6,
      citizenship: "",
    },
    {
      optionId: 160,
      options: [
        {
          id: 160,
          order: 1,
          optionValue: "金融",
          questionid: 34,
          apexValue: "FINANCE",
          expression: "",
        },
        {
          id: 161,
          order: 2,
          optionValue: "银行",
          questionid: 34,
          apexValue: "BANK",
          expression: "",
        },
        {
          id: 162,
          order: 3,
          optionValue: "保险",
          questionid: 34,
          apexValue: "INSURANCE",
          expression: "",
        },
        {
          id: 163,
          order: 4,
          optionValue: "政府",
          questionid: 34,
          apexValue: "GOVERNMENT",
          expression: "",
        },
        {
          id: 164,
          order: 5,
          optionValue: "事业机构",
          questionid: 34,
          apexValue: "INSTITUTION",
          expression: "",
        },
        {
          id: 165,
          order: 6,
          optionValue: "广告公关",
          questionid: 34,
          apexValue: "MARKETING",
          expression: "",
        },
        {
          id: 166,
          order: 7,
          optionValue: "媒体",
          questionid: 34,
          apexValue: "MEDIA",
          expression: "",
        },
        {
          id: 167,
          order: 8,
          optionValue: "艺术文化",
          questionid: 34,
          apexValue: "CULTURE",
          expression: "",
        },
        {
          id: 168,
          order: 9,
          optionValue: "销售",
          questionid: 34,
          apexValue: "SALES",
          expression: "",
        },
        {
          id: 169,
          order: 10,
          optionValue: "贸易",
          questionid: 34,
          apexValue: "TRADING",
          expression: "",
        },
        {
          id: 170,
          order: 11,
          optionValue: "计算机",
          questionid: 34,
          apexValue: "COMPUTER",
          expression: "",
        },
        {
          id: 171,
          order: 12,
          optionValue: "互联网",
          questionid: 34,
          apexValue: "INTERNET",
          expression: "",
        },
        {
          id: 172,
          order: 13,
          optionValue: "通信",
          questionid: 34,
          apexValue: "COMMUNICATION",
          expression: "",
        },
        {
          id: 173,
          order: 14,
          optionValue: "电子技术",
          questionid: 34,
          apexValue: "TECHNOLOGY",
          expression: "",
        },
        {
          id: 174,
          order: 15,
          optionValue: "生产制造",
          questionid: 34,
          apexValue: "MANUFACTURING",
          expression: "",
        },
        {
          id: 175,
          order: 16,
          optionValue: "物流运输",
          questionid: 34,
          apexValue: "LOGIS",
          expression: "",
        },
        {
          id: 176,
          order: 17,
          optionValue: "医药",
          questionid: 34,
          apexValue: "MEDICINE",
          expression: "",
        },
        {
          id: 177,
          order: 18,
          optionValue: "化工",
          questionid: 34,
          apexValue: "CHEMICALS",
          expression: "",
        },
        {
          id: 178,
          order: 19,
          optionValue: "建筑",
          questionid: 34,
          apexValue: "CONSTRUCTION",
          expression: "",
        },
        {
          id: 179,
          order: 20,
          optionValue: "房地产",
          questionid: 34,
          apexValue: "REALESTATE",
          expression: "",
        },
        {
          id: 180,
          order: 21,
          optionValue: "教育",
          questionid: 34,
          apexValue: "EDUCATION",
          expression: "",
        },
        {
          id: 181,
          order: 22,
          optionValue: "法律",
          questionid: 34,
          apexValue: "LEGAL",
          expression: "",
        },
        {
          id: 182,
          order: 23,
          optionValue: "餐饮",
          questionid: 34,
          apexValue: "CATERING",
          expression: "",
        },
        {
          id: 183,
          order: 24,
          optionValue: "娱乐",
          questionid: 34,
          apexValue: "ENTERTAINMENT",
          expression: "",
        },
        {
          id: 184,
          order: 25,
          optionValue: "美容",
          questionid: 34,
          apexValue: "COSMETOLOGY",
          expression: "",
        },
        {
          id: 185,
          order: 26,
          optionValue: "其它",
          questionid: 34,
          apexValue: "OTHERS",
          expression: "",
        },
      ],
      id: 34,
      question: "请选择所属行业",
      type: 1,
      parentId: 22,
      appField: "businessNature",
      title: "所属行业",
      expression: "($23$===106)",
      order: 7,
      citizenship: "",
    },
    {
      optionId: 186,
      options: [
        {
          id: 186,
          order: 1,
          optionValue: "1",
          questionid: 35,
          apexValue: "1",
          expression: "",
        },
        {
          id: 187,
          order: 2,
          optionValue: "2",
          questionid: 35,
          apexValue: "2",
          expression: "",
        },
        {
          id: 188,
          order: 3,
          optionValue: "3",
          questionid: 35,
          apexValue: "3",
          expression: "",
        },
        {
          id: 189,
          order: 4,
          optionValue: "4",
          questionid: 35,
          apexValue: "4",
          expression: "",
        },
        {
          id: 190,
          order: 5,
          optionValue: "5",
          questionid: 35,
          apexValue: "5",
          expression: "",
        },
        {
          id: 191,
          order: 6,
          optionValue: "6",
          questionid: 35,
          apexValue: "6",
          expression: "",
        },
        {
          id: 192,
          order: 7,
          optionValue: "7",
          questionid: 35,
          apexValue: "7",
          expression: "",
        },
        {
          id: 193,
          order: 8,
          optionValue: "8",
          questionid: 35,
          apexValue: "8",
          expression: "",
        },
        {
          id: 194,
          order: 9,
          optionValue: "9",
          questionid: 35,
          apexValue: "9",
          expression: "",
        },
        {
          id: 195,
          order: 10,
          optionValue: "10",
          questionid: 35,
          apexValue: "10",
          expression: "",
        },
        {
          id: 196,
          order: 11,
          optionValue: "11",
          questionid: 35,
          apexValue: "11",
          expression: "",
        },
        {
          id: 197,
          order: 12,
          optionValue: "12",
          questionid: 35,
          apexValue: "12",
          expression: "",
        },
        {
          id: 198,
          order: 13,
          optionValue: "13",
          questionid: 35,
          apexValue: "13",
          expression: "",
        },
        {
          id: 199,
          order: 14,
          optionValue: "14",
          questionid: 35,
          apexValue: "14",
          expression: "",
        },
        {
          id: 200,
          order: 15,
          optionValue: "15",
          questionid: 35,
          apexValue: "15",
          expression: "",
        },
        {
          id: 201,
          order: 16,
          optionValue: "16",
          questionid: 35,
          apexValue: "16",
          expression: "",
        },
        {
          id: 202,
          order: 17,
          optionValue: "17",
          questionid: 35,
          apexValue: "17",
          expression: "",
        },
        {
          id: 203,
          order: 18,
          optionValue: "18",
          questionid: 35,
          apexValue: "18",
          expression: "",
        },
        {
          id: 204,
          order: 19,
          optionValue: "19",
          questionid: 35,
          apexValue: "19",
          expression: "",
        },
        {
          id: 205,
          order: 20,
          optionValue: "20",
          questionid: 35,
          apexValue: "20",
          expression: "",
        },
        {
          id: 206,
          order: 21,
          optionValue: "21",
          questionid: 35,
          apexValue: "21",
          expression: "",
        },
        {
          id: 207,
          order: 22,
          optionValue: "22",
          questionid: 35,
          apexValue: "22",
          expression: "",
        },
        {
          id: 208,
          order: 23,
          optionValue: "23",
          questionid: 35,
          apexValue: "23",
          expression: "",
        },
        {
          id: 209,
          order: 24,
          optionValue: "24",
          questionid: 35,
          apexValue: "24",
          expression: "",
        },
        {
          id: 210,
          order: 25,
          optionValue: "25",
          questionid: 35,
          apexValue: "25",
          expression: "",
        },
        {
          id: 211,
          order: 26,
          optionValue: "26",
          questionid: 35,
          apexValue: "26",
          expression: "",
        },
        {
          id: 212,
          order: 27,
          optionValue: "27",
          questionid: 35,
          apexValue: "27",
          expression: "",
        },
        {
          id: 213,
          order: 28,
          optionValue: "28",
          questionid: 35,
          apexValue: "28",
          expression: "",
        },
        {
          id: 214,
          order: 29,
          optionValue: "29",
          questionid: 35,
          apexValue: "29",
          expression: "",
        },
        {
          id: 215,
          order: 30,
          optionValue: "30",
          questionid: 35,
          apexValue: "30",
          expression: "",
        },
        {
          id: 216,
          order: 31,
          optionValue: "31",
          questionid: 35,
          apexValue: "31",
          expression: "",
        },
        {
          id: 217,
          order: 32,
          optionValue: "32",
          questionid: 35,
          apexValue: "32",
          expression: "",
        },
        {
          id: 218,
          order: 33,
          optionValue: "33",
          questionid: 35,
          apexValue: "33",
          expression: "",
        },
        {
          id: 219,
          order: 34,
          optionValue: "34",
          questionid: 35,
          apexValue: "34",
          expression: "",
        },
        {
          id: 220,
          order: 35,
          optionValue: "35",
          questionid: 35,
          apexValue: "35",
          expression: "",
        },
        {
          id: 221,
          order: 36,
          optionValue: "36",
          questionid: 35,
          apexValue: "36",
          expression: "",
        },
        {
          id: 222,
          order: 37,
          optionValue: "37",
          questionid: 35,
          apexValue: "37",
          expression: "",
        },
        {
          id: 223,
          order: 38,
          optionValue: "38",
          questionid: 35,
          apexValue: "38",
          expression: "",
        },
        {
          id: 224,
          order: 39,
          optionValue: "39",
          questionid: 35,
          apexValue: "39",
          expression: "",
        },
        {
          id: 225,
          order: 40,
          optionValue: "40",
          questionid: 35,
          apexValue: "40",
          expression: "",
        },
      ],
      id: 35,
      question: "请选择工作年限",
      type: 1,
      parentId: 22,
      appField: "yearsEmployed",
      title: "工作年限",
      expression: "($23$===106)",
      order: 8,
      citizenship: "",
    },
    {
      input: "qwe qwe",
      id: 36,
      question: "请填写你所在的单位",
      type: 2,
      parentId: 22,
      appField: "employer",
      title: "所在单位(全称)",
      expression: "($23$===106)",
      order: 9,
      citizenship: "",
    },
    {
      input: "da w",
      id: 101,
      question: "请提供对应上市公司的股票代码",
      type: 3,
      parentId: 100,
      appField: "companySymbols",
      title: "公司股票代码",
      expression: "",
      order: 11,
      citizenship: "",
    },
    {
      input: "qwe 131",
      id: 103,
      question: "请提供相关的组织机构名称",
      type: 2,
      parentId: 102,
      appField: "politicalOrganization",
      title: "机构名称",
      expression: "",
      order: 13,
      citizenship: "",
    },
    {
      input: "qwe 312",
      id: 104,
      question: "请提供您及您的直系亲属姓名（包括前配偶）",
      type: 3,
      parentId: 102,
      appField: "immediateFamily",
      title: "姓名",
      expression: "",
      order: 14,
      citizenship: "",
    },
    {
      input: "ad12312",
      id: 106,
      question: "您或您的家庭成员工作的券商名称",
      type: 2,
      parentId: 105,
      appField: "firmName",
      title: "公司名",
      expression: "",
      order: 16,
      citizenship: "",
    },
    {
      optionId: 252,
      options: [
        {
          id: 250,
          order: 1,
          optionValue: "低",
          questionid: 38,
          apexValue: "Low",
          expression: "",
        },
        {
          id: 251,
          order: 2,
          optionValue: "中",
          questionid: 38,
          apexValue: "Medium",
          expression: "",
        },
        {
          id: 252,
          order: 3,
          optionValue: "高",
          questionid: 38,
          apexValue: "High",
          expression: "",
        },
      ],
      id: 38,
      question: "您的风险容忍度?",
      type: 1,
      parentId: 25,
      appField: "riskTolerance",
      title: "风险容忍度",
      expression: "",
      order: -1,
      citizenship: "",
    },
    {
      optionId: 118,
      options: [
        {
          id: 118,
          order: 1,
          optionValue: "短期",
          questionid: 26,
          apexValue: "SHORT",
          expression: "",
        },
        {
          id: 119,
          order: 2,
          optionValue: "一般",
          questionid: 26,
          apexValue: "AVERAGE",
          expression: "",
        },
        {
          id: 120,
          order: 3,
          optionValue: "长期",
          questionid: 26,
          apexValue: "LONGEST",
          expression: "",
        },
      ],
      id: 26,
      question: "您的投资期限偏好是？",
      type: 1,
      parentId: 25,
      appField: "timeHorizon",
      title: "投资期限偏好",
      expression: "",
      order: -1,
      citizenship: "",
    },
    {
      optionId: 125,
      options: [
        {
          id: 124,
          order: 1,
          optionValue: "保值",
          questionid: 29,
          apexValue: "CAPITAL_PRESERVATION",
          expression: "",
        },
        {
          id: 125,
          order: 2,
          optionValue: "交易利润",
          questionid: 29,
          apexValue: "INCOME",
          expression: "",
        },
        {
          id: 126,
          order: 3,
          optionValue: "增值",
          questionid: 29,
          apexValue: "GROWTH",
          expression: "",
        },
        {
          id: 127,
          order: 4,
          optionValue: "投机",
          questionid: 29,
          apexValue: "SPECULATION",
          expression: "",
        },
        {
          id: 128,
          order: 5,
          optionValue: "其他",
          questionid: 29,
          apexValue: "OTHER",
          expression: "",
        },
      ],
      id: 29,
      question: "你的投资目的是？",
      type: 1,
      parentId: 25,
      appField: "investmentObjective",
      title: "投资目的",
      expression: "",
      order: -1,
      citizenship: "",
    },
    {
      optionId: 130,
      options: [
        {
          id: 129,
          order: 1,
          optionValue: "无",
          questionid: 30,
          apexValue: "NONE",
          expression: "",
        },
        {
          id: 130,
          order: 2,
          optionValue: "有限",
          questionid: 30,
          apexValue: "LIMITED",
          expression: "",
        },
        {
          id: 131,
          order: 3,
          optionValue: "较多",
          questionid: 30,
          apexValue: "GOOD",
          expression: "",
        },
        {
          id: 132,
          order: 4,
          optionValue: "非常丰富",
          questionid: 30,
          apexValue: "EXTENSIVE",
          expression: "",
        },
      ],
      id: 30,
      question: "您有过投资经验吗？",
      type: 1,
      parentId: 25,
      appField: "investmentExperience",
      title: "投资经验",
      expression: "",
      order: -1,
      citizenship: "",
    },
    {
      optionId: 135,
      options: [
        {
          id: 133,
          order: 2,
          optionValue: "0-25000 USD",
          questionid: 31,
          apexValue: "0-25000",
          expression: "",
        },
        {
          id: 135,
          order: 3,
          optionValue: "25001-50000 USD",
          questionid: 31,
          apexValue: "25001-50000",
          expression: "",
        },
        {
          id: 136,
          order: 4,
          optionValue: "50001-100000 USD",
          questionid: 31,
          apexValue: "50001-100000",
          expression: "",
        },
        {
          id: 137,
          order: 5,
          optionValue: "100001-200000 USD",
          questionid: 31,
          apexValue: "100001-200000",
          expression: "",
        },
        {
          id: 138,
          order: 6,
          optionValue: "200001-300000 USD",
          questionid: 31,
          apexValue: "200001-300000",
          expression: "",
        },
        {
          id: 139,
          order: 7,
          optionValue: "300001-500000 USD",
          questionid: 31,
          apexValue: "300001-500000",
          expression: "",
        },
        {
          id: 140,
          order: 8,
          optionValue: "500001-1200000 USD",
          questionid: 31,
          apexValue: "500001-1200000",
          expression: "",
        },
        {
          id: 141,
          order: 9,
          optionValue: "1200001-9999999 USD",
          questionid: 31,
          apexValue: "1200001-9999999",
          expression: "",
        },
      ],
      id: 31,
      question: "您的年收入？",
      type: 1,
      parentId: 27,
      appField: "annualNetIncomeUSD",
      title: "年收入",
      expression: "",
      order: 63,
      citizenship: "",
    },
    {
      optionId: 144,
      options: [
        {
          id: 142,
          order: 1,
          optionValue: "0-50000 USD",
          questionid: 32,
          apexValue: "0-50000",
          expression: "",
        },
        {
          id: 144,
          order: 3,
          optionValue: "50001-100000 USD",
          questionid: 32,
          apexValue: "50001-100000",
          expression: "",
        },
        {
          id: 145,
          order: 4,
          optionValue: "100001-200000 USD",
          questionid: 32,
          apexValue: "100001-200000",
          expression: "",
        },
        {
          id: 226,
          order: 5,
          optionValue: "200001-500000 USD",
          questionid: 32,
          apexValue: "200001-500000",
          expression: "",
        },
        {
          id: 227,
          order: 6,
          optionValue: "500001-1000000 USD",
          questionid: 32,
          apexValue: "500001-1000000",
          expression: "",
        },
        {
          id: 146,
          order: 7,
          optionValue: "1000001-5000000 USD",
          questionid: 32,
          apexValue: "1000001-5000000",
          expression: "",
        },
        {
          id: 147,
          order: 8,
          optionValue: "5000001-9999999 USD",
          questionid: 32,
          apexValue: "5000001-9999999",
          expression: "",
        },
      ],
      id: 32,
      question: "您的流动资金？",
      type: 1,
      parentId: 27,
      appField: "liquidNetWorthUSD",
      title: "流动资金",
      expression: "",
      order: 64,
      citizenship: "",
    },
    {
      optionId: 152,
      options: [
        {
          id: 148,
          order: 1,
          optionValue: "0-50000 USD",
          questionid: 33,
          apexValue: "0-50000",
          expression: "",
        },
        {
          id: 150,
          order: 3,
          optionValue: "50001-100000 USD",
          questionid: 33,
          apexValue: "50001-100000",
          expression: "",
        },
        {
          id: 151,
          order: 4,
          optionValue: "100001-200000 USD",
          questionid: 33,
          apexValue: "100001-200000",
          expression: "",
        },
        {
          id: 152,
          order: 5,
          optionValue: "200001-500000 USD",
          questionid: 33,
          apexValue: "200001-500000",
          expression: "",
        },
        {
          id: 153,
          order: 6,
          optionValue: "500001-1000000 USD",
          questionid: 33,
          apexValue: "500001-1000000",
          expression: "",
        },
        {
          id: 154,
          order: 7,
          optionValue: "1000001-2000000 USD",
          questionid: 33,
          apexValue: "1000001-5000000",
          expression: "",
        },
        {
          id: 334,
          order: 8,
          optionValue: "2000001-5000000 USD",
          questionid: 33,
          apexValue: "1000001-5000000",
          expression: "",
        },
        {
          id: 155,
          order: 9,
          optionValue: "5000001-9999999 USD",
          questionid: 33,
          apexValue: "5000001-9999999",
          expression: "",
        },
      ],
      id: 33,
      question: "您的净资产（总资产刨除负债）？",
      type: 1,
      parentId: 27,
      appField: "totalNetWorthUSD",
      title: "您的净资产（总资产刨除负债）",
      expression: "",
      order: 65,
      citizenship: "",
    },
    {
      optionId: 123,
      options: [
        {
          id: 121,
          order: 1,
          optionValue: "非常重要",
          questionid: 28,
          apexValue: "VERY_IMPORTANT",
          expression: "",
        },
        {
          id: 122,
          order: 2,
          optionValue: "不重要",
          questionid: 28,
          apexValue: "NOT_IMPORTANT",
          expression: "",
        },
        {
          id: 123,
          order: 3,
          optionValue: "一般",
          questionid: 28,
          apexValue: "SOMEWHAT_IMPORTANT",
          expression: "",
        },
      ],
      id: 28,
      question: "您的现金流需求？",
      type: 1,
      parentId: 27,
      appField: "liquidityNeeds",
      title: "流动性需求",
      expression: "",
      order: 66,
      citizenship: "",
    },
    {
      input: "dasd 12312",
      id: 37,
      question: "您的常用银行?",
      type: 2,
      parentId: 27,
      appField: "primaryBanking",
      title: "常用银行",
      expression: "",
      order: 67,
      citizenship: "",
    },
  ],
  survey: [
    { categoryId: 19, questionId: 20, optionId: 95 },
    { categoryId: 19, questionId: 21, optionId: 99 },
    { categoryId: 22, questionId: 23, optionId: 106 },
    { categoryId: 22, questionId: 24, optionId: 110 },
    { categoryId: 22, questionId: 34, optionId: 160 },
    { categoryId: 22, questionId: 35, optionId: 186 },
    { categoryId: 22, questionId: 36, input: "qwe qwe" },
    { categoryId: 100, questionId: 101, input: "da w" },
    { categoryId: 102, questionId: 103, input: "qwe 131" },
    { categoryId: 102, questionId: 104, input: "qwe 312" },
    { categoryId: 105, questionId: 106, input: "ad12312" },
    { categoryId: 25, questionId: 38, optionId: 252 },
    { categoryId: 25, questionId: 26, optionId: 118 },
    { categoryId: 25, questionId: 29, optionId: 125 },
    { categoryId: 25, questionId: 30, optionId: 130 },
    { categoryId: 27, questionId: 31, optionId: 135 },
    { categoryId: 27, questionId: 32, optionId: 144 },
    { categoryId: 27, questionId: 33, optionId: 152 },
    { categoryId: 27, questionId: 28, optionId: 123 },
    { categoryId: 27, questionId: 37, input: "dasd 12312" },
  ],
  InvestmentProfileInit: [
    {
      optionId: 250,
      options: [
        {
          id: 250,
          order: 1,
          optionValue: "低",
          questionid: 38,
          apexValue: "Low",
          expression: "",
        },
        {
          id: 251,
          order: 2,
          optionValue: "中",
          questionid: 38,
          apexValue: "Medium",
          expression: "",
        },
        {
          id: 252,
          order: 3,
          optionValue: "高",
          questionid: 38,
          apexValue: "High",
          expression: "",
        },
      ],
      id: 38,
      question: "您的风险容忍度?",
      type: 1,
      parentId: 25,
      appField: "riskTolerance",
      title: "风险容忍度",
      expression: "",
      order: -1,
      citizenship: "",
    },
    {
      optionId: 119,
      options: [
        {
          id: 118,
          order: 1,
          optionValue: "短期",
          questionid: 26,
          apexValue: "SHORT",
          expression: "",
        },
        {
          id: 119,
          order: 2,
          optionValue: "一般",
          questionid: 26,
          apexValue: "AVERAGE",
          expression: "",
        },
        {
          id: 120,
          order: 3,
          optionValue: "长期",
          questionid: 26,
          apexValue: "LONGEST",
          expression: "",
        },
      ],
      id: 26,
      question: "您的投资期限偏好是？",
      type: 1,
      parentId: 25,
      appField: "timeHorizon",
      title: "投资期限偏好",
      expression: "",
      order: -1,
      citizenship: "",
    },
    {
      optionId: 124,
      options: [
        {
          id: 124,
          order: 1,
          optionValue: "保值",
          questionid: 29,
          apexValue: "CAPITAL_PRESERVATION",
          expression: "",
        },
        {
          id: 125,
          order: 2,
          optionValue: "交易利润",
          questionid: 29,
          apexValue: "INCOME",
          expression: "",
        },
        {
          id: 126,
          order: 3,
          optionValue: "增值",
          questionid: 29,
          apexValue: "GROWTH",
          expression: "",
        },
        {
          id: 127,
          order: 4,
          optionValue: "投机",
          questionid: 29,
          apexValue: "SPECULATION",
          expression: "",
        },
        {
          id: 128,
          order: 5,
          optionValue: "其他",
          questionid: 29,
          apexValue: "OTHER",
          expression: "",
        },
      ],
      id: 29,
      question: "你的投资目的是？",
      type: 1,
      parentId: 25,
      appField: "investmentObjective",
      title: "投资目的",
      expression: "",
      order: -1,
      citizenship: "",
    },
    {
      optionId: 130,
      options: [
        {
          id: 129,
          order: 1,
          optionValue: "无",
          questionid: 30,
          apexValue: "NONE",
          expression: "",
        },
        {
          id: 130,
          order: 2,
          optionValue: "有限",
          questionid: 30,
          apexValue: "LIMITED",
          expression: "",
        },
        {
          id: 131,
          order: 3,
          optionValue: "较多",
          questionid: 30,
          apexValue: "GOOD",
          expression: "",
        },
        {
          id: 132,
          order: 4,
          optionValue: "非常丰富",
          questionid: 30,
          apexValue: "EXTENSIVE",
          expression: "",
        },
      ],
      id: 30,
      question: "您有过投资经验吗？",
      type: 1,
      parentId: 25,
      appField: "investmentExperience",
      title: "投资经验",
      expression: "",
      order: -1,
      citizenship: "",
    },
    {
      optionId: 135,
      options: [
        {
          id: 133,
          order: 2,
          optionValue: "0-25000 USD",
          questionid: 31,
          apexValue: "0-25000",
          expression: "",
        },
        {
          id: 135,
          order: 3,
          optionValue: "25001-50000 USD",
          questionid: 31,
          apexValue: "25001-50000",
          expression: "",
        },
        {
          id: 136,
          order: 4,
          optionValue: "50001-100000 USD",
          questionid: 31,
          apexValue: "50001-100000",
          expression: "",
        },
        {
          id: 137,
          order: 5,
          optionValue: "100001-200000 USD",
          questionid: 31,
          apexValue: "100001-200000",
          expression: "",
        },
        {
          id: 138,
          order: 6,
          optionValue: "200001-300000 USD",
          questionid: 31,
          apexValue: "200001-300000",
          expression: "",
        },
        {
          id: 139,
          order: 7,
          optionValue: "300001-500000 USD",
          questionid: 31,
          apexValue: "300001-500000",
          expression: "",
        },
        {
          id: 140,
          order: 8,
          optionValue: "500001-1200000 USD",
          questionid: 31,
          apexValue: "500001-1200000",
          expression: "",
        },
        {
          id: 141,
          order: 9,
          optionValue: "1200001-9999999 USD",
          questionid: 31,
          apexValue: "1200001-9999999",
          expression: "",
        },
      ],
      id: 31,
      question: "您的年收入？",
      type: 1,
      parentId: 27,
      appField: "annualNetIncomeUSD",
      title: "年收入",
      expression: "",
      order: 63,
      citizenship: "",
    },
    {
      optionId: 144,
      options: [
        {
          id: 142,
          order: 1,
          optionValue: "0-50000 USD",
          questionid: 32,
          apexValue: "0-50000",
          expression: "",
        },
        {
          id: 144,
          order: 3,
          optionValue: "50001-100000 USD",
          questionid: 32,
          apexValue: "50001-100000",
          expression: "",
        },
        {
          id: 145,
          order: 4,
          optionValue: "100001-200000 USD",
          questionid: 32,
          apexValue: "100001-200000",
          expression: "",
        },
        {
          id: 226,
          order: 5,
          optionValue: "200001-500000 USD",
          questionid: 32,
          apexValue: "200001-500000",
          expression: "",
        },
        {
          id: 227,
          order: 6,
          optionValue: "500001-1000000 USD",
          questionid: 32,
          apexValue: "500001-1000000",
          expression: "",
        },
        {
          id: 146,
          order: 7,
          optionValue: "1000001-5000000 USD",
          questionid: 32,
          apexValue: "1000001-5000000",
          expression: "",
        },
        {
          id: 147,
          order: 8,
          optionValue: "5000001-9999999 USD",
          questionid: 32,
          apexValue: "5000001-9999999",
          expression: "",
        },
      ],
      id: 32,
      question: "您的流动资金？",
      type: 1,
      parentId: 27,
      appField: "liquidNetWorthUSD",
      title: "流动资金",
      expression: "",
      order: 64,
      citizenship: "",
    },
    {
      optionId: 150,
      options: [
        {
          id: 148,
          order: 1,
          optionValue: "0-50000 USD",
          questionid: 33,
          apexValue: "0-50000",
          expression: "",
        },
        {
          id: 150,
          order: 3,
          optionValue: "50001-100000 USD",
          questionid: 33,
          apexValue: "50001-100000",
          expression: "",
        },
        {
          id: 151,
          order: 4,
          optionValue: "100001-200000 USD",
          questionid: 33,
          apexValue: "100001-200000",
          expression: "",
        },
        {
          id: 152,
          order: 5,
          optionValue: "200001-500000 USD",
          questionid: 33,
          apexValue: "200001-500000",
          expression: "",
        },
        {
          id: 153,
          order: 6,
          optionValue: "500001-1000000 USD",
          questionid: 33,
          apexValue: "500001-1000000",
          expression: "",
        },
        {
          id: 154,
          order: 7,
          optionValue: "1000001-2000000 USD",
          questionid: 33,
          apexValue: "1000001-5000000",
          expression: "",
        },
        {
          id: 334,
          order: 8,
          optionValue: "2000001-5000000 USD",
          questionid: 33,
          apexValue: "1000001-5000000",
          expression: "",
        },
        {
          id: 155,
          order: 9,
          optionValue: "5000001-9999999 USD",
          questionid: 33,
          apexValue: "5000001-9999999",
          expression: "",
        },
      ],
      id: 33,
      question: "您的净资产（总资产刨除负债）？",
      type: 1,
      parentId: 27,
      appField: "totalNetWorthUSD",
      title: "您的净资产（总资产刨除负债）",
      expression: "",
      order: 65,
      citizenship: "",
    },
    {
      optionId: 123,
      options: [
        {
          id: 121,
          order: 1,
          optionValue: "非常重要",
          questionid: 28,
          apexValue: "VERY_IMPORTANT",
          expression: "",
        },
        {
          id: 122,
          order: 2,
          optionValue: "不重要",
          questionid: 28,
          apexValue: "NOT_IMPORTANT",
          expression: "",
        },
        {
          id: 123,
          order: 3,
          optionValue: "一般",
          questionid: 28,
          apexValue: "SOMEWHAT_IMPORTANT",
          expression: "",
        },
      ],
      id: 28,
      question: "您的现金流需求？",
      type: 1,
      parentId: 27,
      appField: "liquidityNeeds",
      title: "流动性需求",
      expression: "",
      order: 66,
      citizenship: "",
    },
    {
      input: "ada asdasd",
      id: 37,
      question: "您的常用银行?",
      type: 2,
      parentId: 27,
      appField: "primaryBanking",
      title: "常用银行",
      expression: "",
      order: 67,
      citizenship: "",
    },
  ],
  //   InvestmentProfile: [
  //     {
  //       categoryId: 25,
  //       questionId: 38,
  //       optionId: 250,
  //     },
  //     {
  //       categoryId: 25,
  //       questionId: 26,
  //       optionId: 119,
  //     },
  //     {
  //       categoryId: 25,
  //       questionId: 29,
  //       optionId: 124,
  //     },
  //     {
  //       categoryId: 25,
  //       questionId: 30,
  //       optionId: 130,
  //     },
  //     {
  //       categoryId: 27,
  //       questionId: 31,
  //       optionId: 135,
  //     },
  //     {
  //       categoryId: 27,
  //       questionId: 32,
  //       optionId: 144,
  //     },
  //     {
  //       categoryId: 27,
  //       questionId: 33,
  //       optionId: 150,
  //     },
  //     {
  //       categoryId: 27,
  //       questionId: 28,
  //       optionId: 123,
  //     },
  //     {
  //       categoryId: 27,
  //       questionId: 37,
  //       input: "ada asdasd",
  //     },
  //   ],
  //   step3_4_yes_or_no: false,
  //   country: "CHN",
  //   country_name: "中国",
  //   first_name: "asdas12312123",
  //   first_name_pinyin: "dinh",
  //   last_name: "qeq",
  //   last_name_pinyin: "adasd",
  //   birth_country: "CHN",
  //   id_card: "11010519900604755X",
  //   homeAddress: {
  //     address: "123 Drew Street",
  //     city: "asd",
  //     state: "Hải Dương",
  //     postCode: "a1212",
  //   },
  //   residential_other_address: true,
  //   mailAddress: {
  //     address: "123 Drew Street 12312",
  //     city: "asdtt",
  //     state: "Hải Dươngttt",
  //     postCode: "a1212tttt",
  //   },
  //   is_check_card_success: true,
  //   birth_country_name: "中国",
  //   tax_id_number: "asds 1312",
  //   visa_type: "E1",
}
